var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da="./this.program",ea=(a,b)=>{throw b;},fa="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?fa=__filename:ba&&(fa=self.location.href);var ha="",ia,ja;
if(ca){var fs=require("fs");ha=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ha=(new URL(".",fa)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var la=console.log.bind(console),k=console.error.bind(console),ma,na=!1,oa,ka=a=>a.startsWith("file://"),pa,l,t,qa,u,x,ra,sa,A;
function ta(){var a=pa.buffer;l=new Int8Array(a);qa=new Int16Array(a);t=new Uint8Array(a);new Uint16Array(a);u=new Int32Array(a);x=new Uint32Array(a);ra=new Float32Array(a);sa=new Float64Array(a);A=new BigInt64Array(a);new BigUint64Array(a)}var B=0,ua=null;function va(){B++;g.monitorRunDependencies?.(B)}function wa(){B--;g.monitorRunDependencies?.(B);if(0==B&&ua){var a=ua;ua=null;a()}}
function xa(a){g.onAbort?.(a);a="Aborted("+a+")";k(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya;async function za(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ya&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),xa(d)}}async function Ba(a){var b=ya;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return Aa(b,a)}
class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Da=a=>{for(;0<a.length;)a.shift()(g)},Ea=[],Fa=[],Ga=()=>{var a=g.preRun.shift();Fa.push(a)},Ha=!0;function Ia(a,b,c){x[a.xa+16>>2]=0;x[a.xa+4>>2]=b;x[a.xa+8>>2]=c}class Ja{constructor(a){this.xa=a-24}}
var Ka=0,La=0,D=()=>{var a=u[+Ma>>2];Ma+=4;return a},Na=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},E=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Na(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Oa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=
b.slice(0,-1);return a+b},Pa=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Qa=a=>{(Qa=Pa())(a)},Ra=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Na(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Sa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0)=>{var c=
b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Sa)return Sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ta=[],Ua=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:
2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},H=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;f++}}b[c]=0;return c-e},Va=a=>{var b=Array(Ua(a)+1);a=H(a,b,0,b.length);
b.length=a;return b},Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],ra:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close(a){a.tty.ra.fsync(a.tty)},fsync(a){a.tty.ra.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ra.Ia)throw new J(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.ra.Ia(a.tty)}catch(q){throw new J(29);}if(void 0===h&&0===e)throw new J(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ra.Ea)throw new J(60);try{for(var e=0;e<d;e++)a.tty.ra.Ea(a.tty,b[c+e])}catch(f){throw new J(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},$a={Ia(){a:{if(!Ta.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ta=Va(a)}a=Ta.shift()}return a},Ea(a,b){null===b||10===b?(la(F(a.output)),a.output=[]):0!=
b&&a.output.push(b)},fsync(a){0<a.output?.length&&(la(F(a.output)),a.output=[])},Sa(){return{fb:25856,hb:5,eb:191,gb:35387,cb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ta(){return 0},Ua(){return[24,80]}},ab={Ea(a,b){null===b||10===b?(k(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(k(F(a.output)),a.output=[])}},K={ma:null,pa(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);
K.ma||(K.ma={dir:{node:{oa:K.ha.oa,na:K.ha.na,lookup:K.ha.lookup,wa:K.ha.wa,rename:K.ha.rename,unlink:K.ha.unlink,rmdir:K.ha.rmdir,readdir:K.ha.readdir,symlink:K.ha.symlink},stream:{la:K.ga.la}},file:{node:{oa:K.ha.oa,na:K.ha.na},stream:{la:K.ga.la,read:K.ga.read,write:K.ga.write,Da:K.ga.Da,Pa:K.ga.Pa}},link:{node:{oa:K.ha.oa,na:K.ha.na,readlink:K.ha.readlink},stream:{}},Ha:{node:{oa:K.ha.oa,na:K.ha.na},stream:bb}});c=cb(a,b,c,d);L(c.mode)?(c.ha=K.ma.dir.node,c.ga=K.ma.dir.stream,c.fa={}):32768===
(c.mode&61440)?(c.ha=K.ma.file.node,c.ga=K.ma.file.stream,c.ia=0,c.fa=null):40960===(c.mode&61440)?(c.ha=K.ma.link.node,c.ga=K.ma.link.stream):8192===(c.mode&61440)&&(c.ha=K.ma.Ha.node,c.ga=K.ma.Ha.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.fa[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},kb(a){return a.fa?a.fa.subarray?a.fa.subarray(0,a.ia):new Uint8Array(a.fa):new Uint8Array(0)},ha:{oa(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=
a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ia:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},na(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ia!=b&&(0==b?(a.fa=null,a.ia=0):(c=a.fa,a.fa=new Uint8Array(b),c&&a.fa.set(c.subarray(0,Math.min(b,a.ia))),a.ia=b)))},lookup(){K.ya||(K.ya=
new J(44),K.ya.stack="<generic error, no stack>");throw K.ya;},wa(a,b,c,d){return K.createNode(a,b,c,d)},rename(a,b,c){try{var d=M(b,c)}catch(f){}if(d){if(L(a.mode))for(var e in d.fa)throw new J(55);db(d)}delete a.parent.fa[a.name];b.fa[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.fa[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=M(a,b),d;for(d in c.fa)throw new J(55);delete a.fa[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.fa)]},
symlink(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},ga:{read(a,b,c,d,e){var f=a.node.fa;if(e>=a.node.ia)return 0;a=Math.min(a.node.ia-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===l.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.fa||a.fa.subarray)){if(f)return a.fa=b.subarray(c,c+d),a.ia=d;if(0===a.ia&&
0===e)return a.fa=b.slice(c,c+d),a.ia=d;if(e+d<=a.ia)return a.fa.set(b.subarray(c,c+d),e),d}f=e+d;var h=a.fa?a.fa.length:0;h>=f||(f=Math.max(f,h*(1048576>h?2:1.125)>>>0),0!=h&&(f=Math.max(f,256)),h=a.fa,a.fa=new Uint8Array(f),0<a.ia&&a.fa.set(h.subarray(0,a.ia),0));if(a.fa.subarray&&b.subarray)a.fa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.fa[e+f]=b[c+f];a.ia=Math.max(a.ia,e+d);return d},la(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ia);if(0>b)throw new J(28);
return b},Da(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.fa;if(e&2||!a||a.buffer!==l.buffer){d=!0;xa();e=void 0;if(!e)throw new J(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);l.set(a,e)}}else d=!1,e=a.byteOffset;return{xa:e,bb:d}},Pa(a,b,c,d){K.ga.write(a,b,0,d,c,!1);return 0}}},eb=async a=>{a=await ia(a);return new Uint8Array(a)},fb=[],gb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Ia(Browser);var e=!1;fb.forEach(f=>{!e&&
f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},hb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ib=null,jb={},N=[],kb=1,O=null,lb=!1,mb=!0,nb={},J=class{name="ErrnoError";constructor(a){this.ja=a}},ob=class{ka={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.ka.flags}set flags(a){this.ka.flags=a}get position(){return this.ka.position}set position(a){this.ka.position=a}},pb=class{ha={};ga={};ta=null;constructor(a,b,c,d){a||=this;this.parent=a;this.pa=
a.pa;this.id=kb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Wa(){return L(this.mode)}get Va(){return 8192===(this.mode&61440)}};
function P(a,b={}){if(!a)throw new J(44);b.za??(b.za=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(q=>!!q);for(var d=ib,e="/",f=0;f<a.length;f++){var h=f===a.length-1;if(h&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Oa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=E(e+"/"+a[f]);try{d=M(d,a[f])}catch(q){if(44===q?.ja&&h&&b.Za)return{path:e};throw q;}!d.ta||h&&!b.za||(d=d.ta.root);if(40960===(d.mode&61440)&&(!h||b.va)){if(!d.ha.readlink)throw new J(52);
d=d.ha.readlink(d);"/"===d.charAt(0)||(d=Oa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new J(32);}function qb(a){for(var b;;){if(a===a.parent)return a=a.pa.Oa,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function rb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}
function db(a){var b=rb(a.parent.id,a.name);if(O[b]===a)O[b]=a.sa;else for(b=O[b];b;){if(b.sa===a){b.sa=a.sa;break}b=b.sa}}function M(a,b){var c=L(a.mode)?(c=sb(a,"x"))?c:a.ha.lookup?0:2:54;if(c)throw new J(c);for(c=O[rb(a.id,b)];c;c=c.sa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ha.lookup(a,b)}function cb(a,b,c,d){a=new pb(a,b,c,d);b=rb(a.parent.id,a.name);a.sa=O[b];return O[b]=a}function L(a){return 16384===(a&61440)}
function tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function sb(a,b){if(mb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ub(a,b){if(!L(a.mode))return 54;try{return M(a,b),20}catch(c){}return sb(a,"wx")}function vb(a){if(!a)throw new J(63);return a}function Q(a){a=N[a];if(!a)throw new J(8);return a}
function wb(a,b=-1){a=Object.assign(new ob,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!N[b])break a;throw new J(33);}a.fd=b;return N[b]=a}function xb(a,b=-1){a=wb(a,b);a.ga?.jb?.(a);return a}function yb(a,b){var c=null?.ga.na,d=c?null:a;c??=a.ha.na;vb(c);c(d,b)}var bb={open(a){a.ga=jb[a.node.rdev].ga;a.ga.open?.(a)},la(){throw new J(70);}};function Ya(a,b){jb[a]={ga:b}}
function zb(a,b){var c="/"===b;if(c&&ib)throw new J(10);if(!c&&b){var d=P(b,{za:!1});b=d.path;d=d.node;if(d.ta)throw new J(10);if(!L(d.mode))throw new J(54);}b={type:a,lb:{},Oa:b,Ya:[]};a=a.pa(b);a.pa=b;b.root=a;c?ib=a:d&&(d.ta=b,d.pa&&d.pa.Ya.push(b))}function Ab(a,b,c){var d=P(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new J(28);if("."===a||".."===a)throw new J(20);var e=ub(d,a);if(e)throw new J(e);if(!d.ha.wa)throw new J(63);return d.ha.wa(d,a,b,c)}
function Bb(a,b=438){return Ab(a,b&4095|32768,0)}function S(a,b=511){return Ab(a,b&1023|16384,0)}function Cb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ab(a,b|8192,c)}function Db(a,b){if(!Ra(a))throw new J(44);var c=P(b,{parent:!0}).node;if(!c)throw new J(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=ub(c,b);if(d)throw new J(d);if(!c.ha.symlink)throw new J(63);c.ha.symlink(c,b,a)}
function Eb(a){var b=P(a,{parent:!0}).node;if(!b)throw new J(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=M(b,a);a:{try{var d=M(b,a)}catch(f){d=f.ja;break a}var e=sb(b,"wx");d=e?e:L(d.mode)?31:0}if(d)throw new J(d);if(!b.ha.unlink)throw new J(63);if(c.ta)throw new J(10);b.ha.unlink(b,a);db(c)}function Fb(a,b){a="string"==typeof a?P(a,{va:!0}).node:a;yb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),ib:void 0})}
function Gb(a,b,c=438){if(""===a)throw new J(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=P(a,{va:!(b&131072),Za:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new J(20);}else{if(e)throw new J(31);d=Ab(a,c|511,0);f=!0}if(!d)throw new J(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!L(d.mode))throw new J(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:L(d.mode)&&("r"!==tb(b)||b&576)?31:sb(d,tb(b)):44))throw new J(e);if(b&512&&!f){e=d;e="string"==typeof e?P(e,{va:!0}).node:e;if(L(e.mode))throw new J(31);if(32768!==(e.mode&61440))throw new J(28);var h=sb(e,"w");if(h)throw new J(h);yb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=wb({node:d,path:qb(d),flags:b,seekable:!0,position:0,ga:d.ga,ab:[],error:!1});e.ga.open&&e.ga.open(e);f&&Fb(d,c&511);!g.logReadFiles||b&1||a in nb||(nb[a]=1);return e}
function Hb(a){if(null===a.fd)throw new J(8);a.Ba&&(a.Ba=null);try{a.ga.close&&a.ga.close(a)}catch(b){throw b;}finally{N[a.fd]=null}a.fd=null}function Ib(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.ga.la)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.ga.la(a,b,c);a.ab=[]}
function Jb(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(L(a.node.mode))throw new J(31);if(!a.ga.write)throw new J(28);a.seekable&&a.flags&1024&&Ib(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new J(70);b=a.ga.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function Kb(a,b){a="string"==typeof a?a:qb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=E(a+"/"+c);try{S(d)}catch(e){if(20!=e.ja)throw e;}a=d}}return d}function Lb(a,b,c,d){a=E(("string"==typeof a?a:qb(a))+"/"+b);return Bb(a,hb(c,d))}
function Mb(a,b,c,d,e,f){var h=b;a&&(a="string"==typeof a?a:qb(a),h=b?E(a+"/"+b):a);a=hb(d,e);h=Bb(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Fb(h,a|146);b=Gb(h,577);Jb(b,c,0,c.length,0,f);Hb(b);Fb(h,a)}}
function T(a,b,c,d){a=E(("string"==typeof a?a:qb(a))+"/"+b);b=hb(!!c,!!d);T.Ma??(T.Ma=64);var e=T.Ma++<<8|0;Ya(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,h,q,r){for(var m=0,n=0;n<r;n++){try{var p=c()}catch(v){throw new J(29);}if(void 0===p&&0===m)throw new J(6);if(null===p||void 0===p)break;m++;h[q+n]=p}m&&(f.node.atime=Date.now());return m},write(f,h,q,r){for(var m=0;m<r;m++)try{d(h[q+m])}catch(n){throw new J(29);}r&&(f.node.mtime=f.node.ctime=Date.now());return m}});return Cb(a,
b,e)}function Nb(a){if(!(a.Va||a.Wa||a.link||a.fa)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.fa=ja(a.url),a.ia=a.fa.length}catch(b){throw new J(29);}}}
function Ob(a,b,c,d,e){class f{Ca=!1;ka=[];Aa=void 0;Ka=0;Ja=0;get(n){if(!(n>this.length-1||0>n)){var p=n%this.chunkSize;return this.Aa(n/this.chunkSize|0)[p]}}Xa(n){this.Aa=n}La(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var p=Number(n.getResponseHeader("Content-length")),v,y=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=(v=n.getResponseHeader("Content-Encoding"))&&"gzip"===
v;var w=1048576;y||(w=p);var z=this;z.Xa(G=>{var R=G*w,I=(G+1)*w-1;I=Math.min(I,p-1);if("undefined"==typeof z.ka[G]){var tc=z.ka;if(R>I)throw Error("invalid range ("+R+", "+I+") or no bytes requested!");if(I>p-1)throw Error("only "+p+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);p!==w&&C.setRequestHeader("Range","bytes="+R+"-"+I);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=C.status&&
300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);R=void 0!==C.response?new Uint8Array(C.response||[]):Va(C.responseText||"");tc[G]=R}if("undefined"==typeof z.ka[G])throw Error("doXHR failed!");return z.ka[G]});if(n||!p)w=p=1,w=p=this.Aa(0).length,la("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ka=p;this.Ja=w;this.Ca=!0}get length(){this.Ca||this.La();return this.Ka}get chunkSize(){this.Ca||this.La();return this.Ja}}if("undefined"!=
typeof XMLHttpRequest){if(!ba)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;var q=void 0}else q=c,h=void 0;var r=Lb(a,b,d,e);h?r.fa=h:q&&(r.fa=null,r.url=q);Object.defineProperties(r,{ia:{get:function(){return this.fa.length}}});var m={};Object.keys(r.ga).forEach(n=>{var p=r.ga[n];m[n]=(...v)=>{Nb(r);return p(...v)}});m.read=(n,p,v,y,w)=>{Nb(r);n=n.node.fa;if(w>=n.length)p=0;else{y=Math.min(n.length-w,y);if(n.slice)for(var z=
0;z<y;z++)p[v+z]=n[w+z];else for(z=0;z<y;z++)p[v+z]=n.get(w+z);p=y}return p};m.Da=()=>{Nb(r);xa();throw new J(48);};r.ga=m;return r}var U={};function Pb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Q(a).path;if(0==b.length)throw new J(44);return a+"/"+b}
var Ma=void 0,Qb=[],Rb,Sb=a=>{var b=Qb[a];b||(Qb[a]=b=Rb.get(a));return b},Tb=a=>({width:x[a>>2],height:x[a+4>>2],depthOrArrayLayers:x[a+8>>2]}),Ub=[,"uniform","storage","read-only-storage"],Vb=[,"filtering","non-filtering","comparison"],Wb=[,"write-only","read-only","read-write"],Xb=[,"all","stencil-only","depth-only"],Yb=[,"1d","2d","3d"],Zb=[,"r8unorm","r8snorm","r8uint","r8sint","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16uint",
"rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb",
"bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb",
"astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],$b=[,"float","unfilterable-float","depth","sint","uint"],ac=[,"1d","2d","2d-array","cube","cube-array","3d"],V,bc,cc,W,X,dc,Y,ec,fc,
gc,hc,ic,jc,kc,lc,mc,nc={},pc=()=>{if(!oc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in nc)void 0===nc[b]?delete a[b]:a[b]=nc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);oc=c}return oc},oc,qc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";qc.Ga||(qc.Ga={});qc.Ga[a]||(qc.Ga[a]=1,ca&&(a="warning: "+a),k(a))},rc=a=>{if(!na)try{if(a(),
!Ha)try{oa=oa=a=oa,Ha||(g.onExit?.(a),na=!0),ea(a,new Ca(a))}catch(b){b instanceof Ca||"unwind"==b||ea(1,b)}}catch(b){b instanceof Ca||"unwind"==b||ea(1,b)}},wc=(a,b,c,d)=>{var e={string:m=>{var n=0;if(null!==m&&void 0!==m&&0!==m){n=Ua(m)+1;var p=sc(n);H(m,t,p,n);n=p}return n},array:m=>{var n=sc(m.length);l.set(m,n);return n}};a=g["_"+a];var f=[],h=0;if(d)for(var q=0;q<d.length;q++){var r=e[c[q]];r?(0===h&&(h=uc()),f[q]=r(d[q])):f[q]=d[q]}c=a(...f);return c=function(m){0!==h&&vc(h);return"string"===
b?m?F(t,m):"":"boolean"===b?!!m:m}(c)};O=Array(4096);zb(K,"/");S("/tmp");S("/home");S("/home/web_user");(function(){S("/dev");Ya(259,{read:()=>0,write:(d,e,f,h)=>h,la:()=>0});Cb("/dev/null",259);Xa(1280,$a);Xa(1536,ab);Cb("/dev/tty",1280);Cb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Qa(a),b=a.byteLength);return a[--b]};T("/dev","random",c);T("/dev","urandom",c);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");zb({pa(){var b=cb(a,"fd",16895,73);b.ga={la:K.ga.la};b.ha={lookup(c,d){c=+d;var e=Q(c);c={parent:null,pa:{Oa:"fake"},ha:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(N.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();
(()=>{function a(){this.qa={};this.ka=1;this.create=function(b,c={}){var d=this.ka++;c.Fa=1;c.object=b;this.qa[d]=c;return d};this.get=function(b){if(b)return this.qa[b].object};this.Qa=function(b){this.qa[b].Fa++};this.release=function(b){var c=this.qa[b];c.Fa--;0>=c.Fa&&delete this.qa[b]}}new a;new a;new a;V=new a;bc=new a;cc=new a;W=new a;new a;X=new a;dc=new a;Y=new a;ec=new a;fc=new a;gc=new a;hc=new a;ic=new a;jc=new a;new a;kc=new a;lc=new a;new a;new a})();g.noExitRuntime&&(Ha=g.noExitRuntime);
g.preloadPlugins&&(fb=g.preloadPlugins);g.print&&(la=g.print);g.printErr&&(k=g.printErr);g.wasmBinary&&(ma=g.wasmBinary);g.thisProgram&&(da=g.thisProgram);g.addRunDependency=va;g.removeRunDependency=wa;g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>wc(a,b,c,f)};
g.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return l[a];case "i8":return l[a];case "i16":return qa[a>>1];case "i32":return u[a>>2];case "i64":return A[a>>3];case "float":return ra[a>>2];case "double":return sa[a>>3];case "*":return x[a>>2];default:xa(`invalid type for getValue: ${b}`)}};
g.FS_createPreloadedFile=(a,b,c,d,e,f,h,q,r,m)=>{function n(y){function w(z){m?.();q||Mb(a,b,z,d,e,r);f?.();wa(v)}gb(y,p,w,()=>{h?.();wa(v)})||w(y)}var p=b?Ra(E(a+"/"+b)):a,v=`cp ${p}`;va(v);"string"==typeof c?eb(c).then(n,h):n(c)};g.FS_unlink=(...a)=>Eb(...a);g.FS_createPath=(...a)=>Kb(...a);g.FS_createDevice=(...a)=>T(...a);g.FS_createDataFile=(...a)=>Mb(...a);g.FS_createLazyFile=(...a)=>Ob(...a);
var xc,yc,vc,sc,uc,zc={s:(a,b,c)=>{Ia(new Ja(a),b,c);Ka=a;La++;throw Ka;},v:function(a,b,c){Ma=c;try{var d=Q(a);switch(b){case 0:var e=D();if(0>e)break;for(;N[e];)e++;return xb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=D(),d.flags|=e,0;case 12:return e=D(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.ja}},M:function(a,b,c){Ma=c;try{var d=Q(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;
if(d.tty.ra.Sa){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=D();u[e>>2]=25856;u[e+4>>2]=5;u[e+8>>2]=191;u[e+12>>2]=35387;for(var f=0;32>f;f++)l[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.ra.Ta)for(e=D(),a=[],f=0;32>f;f++)a.push(l[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=D();return u[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=D();if(!d.ga.Ra)throw new J(59);
return d.ga.Ra(d,b,e);case 21523:if(!d.tty)return-59;d.tty.ra.Ua&&(f=[24,80],e=D(),qa[e>>1]=f[0],qa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof U||"ErrnoError"!==h.name)throw h;return-h.ja}},E:function(a,b,c){try{return b=b?F(t,b):"",b=Pb(a,b),S(b,c),0}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.ja}},O:function(a,b,c,d){Ma=d;try{b=b?F(t,b):"";b=Pb(a,b);var e=d?D():0;return Gb(b,
c,e).fd}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.ja}},F:function(a,b){try{a=a?F(t,a):"";var c=P(a,{va:!0}).node;var d=vb(c.ha.oa)(c);u[b>>2]=d.dev;u[b+4>>2]=d.mode;x[b+8>>2]=d.nlink;u[b+12>>2]=d.uid;u[b+16>>2]=d.gid;u[b+20>>2]=d.rdev;A[b+24>>3]=BigInt(d.size);u[b+32>>2]=4096;u[b+36>>2]=d.blocks;var e=d.atime.getTime(),f=d.mtime.getTime(),h=d.ctime.getTime();A[b+40>>3]=BigInt(Math.floor(e/1E3));x[b+48>>2]=e%1E3*1E6;A[b+56>>3]=BigInt(Math.floor(f/1E3));x[b+64>>2]=f%
1E3*1E6;A[b+72>>3]=BigInt(Math.floor(h/1E3));x[b+80>>2]=h%1E3*1E6;A[b+88>>3]=BigInt(d.ino);return 0}catch(q){if("undefined"==typeof U||"ErrnoError"!==q.name)throw q;return-q.ja}},J:()=>xa(""),Q:a=>{do{var b=x[a>>2];a+=4;var c=x[a>>2];a+=4;var d=x[a>>2];a+=4;b=b?F(t,b):"";Kb("/",Oa(b));Mb(b,null,l.subarray(d,d+c),!0,!0,!0)}while(x[a>>2])},G:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();x[a>>2]=60*Math.max(f,e);u[b>>2]=Number(f!=
e);b=h=>{var q=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(q/60)).padStart(2,"0")}${String(q%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(H(a,t,c,17),H(b,t,d,17)):(H(a,t,d,17),H(b,t,c,17))},P:function(a,b,c){if(!(0<=a&&3>=a))return 28;A[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},N:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-
pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},B:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},q:()=>{if(void 0===mc){var a=g.preinitializedWebGPUDevice,b={$a:bc.create(a.queue)};mc=V.create(a,b)}V.Qa(mc);return mc},H:(a,b)=>{var c=0,d=0,e;for(e of pc()){var f=b+c;x[a+d>>2]=f;c+=H(e,t,f,Infinity)+1;d+=4}return 0},I:(a,b)=>{var c=pc();x[a>>2]=c.length;a=0;
for(var d of c)a+=Ua(d)+1;x[b>>2]=a;return 0},t:function(a){try{var b=Q(a);Hb(b);return 0}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return c.ja}},K:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var f,h=b=0;h<c;h++){var q=x[a>>2],r=x[a+4>>2];a+=8;var m=e,n=q,p=r,v=f,y=l;if(0>p||0>v)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(L(m.node.mode))throw new J(31);if(!m.ga.read)throw new J(28);var w="undefined"!=typeof v;if(!w)v=m.position;else if(!m.seekable)throw new J(70);
var z=m.ga.read(m,y,n,p,v);w||(m.position+=z);var G=z;if(0>G){var R=-1;break a}b+=G;if(G<r)break;"undefined"!=typeof f&&(f+=G)}R=b}x[d>>2]=R;return 0}catch(I){if("undefined"==typeof U||"ErrnoError"!==I.name)throw I;return I.ja}},L:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Q(a);Ib(e,b,c);A[d>>3]=BigInt(e.position);e.Ba&&0===b&&0===c&&(e.Ba=null);return 0}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return f.ja}},u:function(a,
b,c,d){try{a:{var e=Q(a);a=b;for(var f,h=b=0;h<c;h++){var q=x[a>>2],r=x[a+4>>2];a+=8;var m=Jb(e,l,q,r,f);if(0>m){var n=-1;break a}b+=m;if(m<r)break;"undefined"!=typeof f&&(f+=m)}n=b}x[d>>2]=n;return 0}catch(p){if("undefined"==typeof U||"ErrnoError"!==p.name)throw p;return p.ja}},o:a=>dc.release(a),A:(a,b,c)=>{a=Y.qa[a];0===c&&qc();-1==c&&(c=void 0);if(2!==a.Na)return 0;try{var d=a.object.getMappedRange(b,c)}catch(f){return 0}var e=yc(16,d.byteLength);t.fill(0,e,e+d.byteLength);a.ua.push(()=>{(new Uint8Array(d)).set(t.subarray(e,
e+d.byteLength));xc(e)});return e},C:(a,b,c,d,e,f)=>{a=Y.qa[a];a.Na=b;a.ua=[];a=a.object;-1==d&&(d=void 0);a.mapAsync(b,c,d).then(()=>{rc(()=>{Sb(e)(0,f)})},()=>{rc(()=>{Sb(e)(1,f)})})},w:a=>Y.release(a),z:a=>{a=Y.qa[a];if(a.ua){for(var b of a.ua)b();a.ua=void 0;a.object.unmap()}},g:a=>cc.release(a),d:(a,b)=>{if(b){var c=x[b+8>>2];c=0!==c?{querySet:hc.get(x[c>>2]),beginningOfPassWriteIndex:x[c+4>>2],endOfPassWriteIndex:x[c+8>>2]}:void 0;c={label:void 0,timestampWrites:c};(b=x[b+4>>2])&&(c.label=b?
F(t,b):"")}a=W.get(a);return X.create(a.beginComputePass(c))},R:function(a,b,c,d,e,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=W.get(a);b=Y.get(b);d=Y.get(d);a.copyBufferToBuffer(b,c,d,e,f)},X:(a,b,c,d)=>{a=W.get(a);d=Tb(d);var e=a.copyTextureToBuffer,f=fc.get(x[b+4>>2]),h=b+12;b={texture:f,mipLevel:x[b+8>>2],origin:{x:x[h>>2],y:x[h+4>>2],z:x[h+8>>2]},aspect:Xb[x[b+24>>
2]]};f=c+8;h=x[f+16>>2];var q=x[f+20>>2];f={offset:4294967296*x[f+4+8>>2]+x[f+8>>2],bytesPerRow:4294967295===h?void 0:h,rowsPerImage:4294967295===q?void 0:q};f.buffer=Y.get(x[c+32>>2]);e.call(a,b,f,d)},c:a=>{a=W.get(a);return cc.create(a.finish())},h:a=>W.release(a),j:(a,b,c,d)=>{X.get(a).dispatchWorkgroups(b,c,d)},i:a=>{X.get(a).end()},k:(a,b,c,d,e)=>{a=X.get(a);c=dc.get(c);if(0==d)a.setBindGroup(b,c);else{for(var f=[],h=0;h<d;h++,e+=4)f.push(x[e>>2]);a.setBindGroup(b,c,f)}},l:(a,b)=>{a=X.get(a);
b=kc.get(b);a.setPipeline(b)},S:(a,b)=>{a=kc.get(a);return ic.create(a.getBindGroupLayout(b))},e:(a,b)=>{for(var c=ic.get(x[b+8>>2]),d=x[b+12>>2],e=x[b+16>>2],f=[],h=0;h<d;++h){var q=f,r=q.push;var m=e+40*h;var n=x[m+8>>2],p=x[m+32>>2],v=x[m+36>>2],y=x[m+4>>2];n?(p=m+24,p=x[p>>2]+4294967296*u[p+4>>2],-1==p&&(p=void 0),m={binding:y,resource:{buffer:Y.get(n),offset:4294967296*x[m+4+16>>2]+x[m+16>>2],size:p}}):m=p?{binding:y,resource:ec.get(p)}:{binding:y,resource:gc.get(v)};r.call(q,m)}c={label:void 0,
layout:c,entries:f};(b=x[b+4>>2])&&(c.label=b?F(t,b):"");a=V.get(a);return dc.create(a.createBindGroup(c))},p:(a,b)=>{for(var c=x[b+8>>2],d=x[b+12>>2],e=[],f=0;f<c;++f){var h=e,q=h.push,r=d+80*f,m=x[r+4>>2],n=x[r+8>>2];var p=r+16;var v=x[p+4>>2];p=v?{type:Ub[v],hasDynamicOffset:!!x[p+8>>2],minBindingSize:4294967296*x[p+4+16>>2]+x[p+16>>2]}:void 0;v=(v=x[r+40+4>>2])?{type:Vb[v]}:void 0;var y=r+48;var w=x[y+4>>2];y=w?{sampleType:$b[w],viewDimension:ac[x[y+8>>2]],multisampled:!!x[y+12>>2]}:void 0;r+=
64;r=(w=x[r+4>>2])?{access:Wb[w],format:Zb[x[r+8>>2]],viewDimension:ac[x[r+12>>2]]}:void 0;q.call(h,{binding:m,visibility:n,buffer:p,sampler:v,texture:y,storageTexture:r})}c={entries:e};(b=x[b+4>>2])&&(c.label=b?F(t,b):"");a=V.get(a);return ic.create(a.createBindGroupLayout(c))},r:(a,b)=>{var c=!!x[b+24>>2],d={label:void 0,usage:x[b+8>>2],size:4294967296*x[b+4+16>>2]+x[b+16>>2],mappedAtCreation:c};(b=x[b+4>>2])&&(d.label=b?F(t,b):"");b=V.get(a);a={};d=Y.create(b.createBuffer(d),a);c&&(a.Na=2,a.ua=
[]);return d},a:(a,b)=>{if(b){var c={label:void 0};(b=x[b+4>>2])&&(c.label=b?F(t,b):"")}a=V.get(a);return W.create(a.createCommandEncoder(c))},f:(a,b)=>{var c=(c=x[b+8>>2])?jc.get(c):"auto";var d;if(d=b+12){var e=lc.get(x[d+4>>2]);var f=x[d+12>>2];var h=x[d+16>>2];if(f){for(var q={},r=0;r<f;++r){var m=h+16*r;var n=(n=x[m+4>>2])?F(t,n):"";q[n]=sa[m+8>>3]}f=q}else f=void 0;e={module:e,constants:f};(d=x[d+8>>2])&&(e.entryPoint=d?F(t,d):"");d=e}else d=void 0;c={label:void 0,layout:c,compute:d};(b=x[b+
4>>2])&&(c.label=b?F(t,b):"");a=V.get(a);return kc.create(a.createComputePipeline(c))},n:(a,b)=>{for(var c=x[b+8>>2],d=x[b+12>>2],e=[],f=0;f<c;++f)e.push(ic.get(x[d+4*f>>2]));c={label:void 0,bindGroupLayouts:e};(b=x[b+4>>2])&&(c.label=b?F(t,b):"");a=V.get(a);return jc.create(a.createPipelineLayout(c))},m:(a,b)=>{var c=x[b>>2],d=x[c+4>>2],e={label:void 0,code:""};(b=x[b+4>>2])&&(e.label=b?F(t,b):"");switch(d){case 5:d=x[c+12>>2]>>2;e.code=x.subarray(d,d+x[c+8>>2]);break;case 6:(c=x[c+8>>2])&&(e.code=
c?F(t,c):"")}a=V.get(a);return lc.create(a.createShaderModule(e))},y:(a,b)=>{var c={label:void 0,size:Tb(b+16),mipLevelCount:x[b+32>>2],sampleCount:x[b+36>>2],dimension:Yb[x[b+12>>2]],format:Zb[x[b+28>>2]],usage:x[b+8>>2]},d=x[b+4>>2];d&&(c.label=d?F(t,d):"");if(d=x[b+40>>2])b=x[b+44>>2],c.viewFormats=Array.from(u.subarray(b>>2,b+4*d>>2),e=>Zb[e]);a=V.get(a);return fc.create(a.createTexture(c))},W:a=>{a=V.qa[a].$a;bc.Qa(a);return a},b:(a,b,c)=>{a=bc.get(a);b=Array.from(u.subarray(c>>2,c+4*b>>2),d=>
cc.get(d));a.submit(b)},D:function(a,b,c,d,e){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=bc.get(a);b=Y.get(b);a.writeBuffer(b,c,t.subarray(d,d+e),0,e)},T:a=>lc.release(a),x:(a,b)=>{if(b){var c=x[b+20>>2];var d=x[b+28>>2];c={format:Zb[x[b+8>>2]],dimension:ac[x[b+12>>2]],baseMipLevel:x[b+16>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:x[b+24>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Xb[x[b+32>>2]]};(b=x[b+4>>2])&&(c.label=b?F(t,b):"")}a=fc.get(a);return gc.create(a.createView(c))},
U:a=>fc.release(a),V:a=>gc.release(a)},Z;(async function(){function a(c){Z=c.exports;pa=Z.Y;ta();Rb=Z._;c=Z;g._GenerateChunk=c.$;xc=c.aa;yc=c.ba;vc=c.ca;sc=c.da;uc=c.ea;wa("wasm-instantiate");return Z}va("wasm-instantiate");var b={a:zc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ya??=g.locateFile?g.locateFile("terraingen.wasm",ha):ha+"terraingen.wasm";return a((await Ba(b)).instance)})();
function Ac(){function a(){g.calledRun=!0;if(!na){if(!g.noFSInit&&!lb){var b,c;lb=!0;b??=g.stdin;c??=g.stdout;d??=g.stderr;b?T("/dev","stdin",b):Db("/dev/tty","/dev/stdin");c?T("/dev","stdout",null,c):Db("/dev/tty","/dev/stdout");d?T("/dev","stderr",null,d):Db("/dev/tty1","/dev/stderr");Gb("/dev/stdin",0);Gb("/dev/stdout",1);Gb("/dev/stderr",1)}Z.Z();mb=!1;g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var d=g.postRun.shift();Ea.push(d)}Da(Ea)}}
if(0<B)ua=Ac;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ga();Da(Fa);0<B?ua=Ac:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();Ac();
